---
name: bandit
description: Bandit, a security linter from PyCQA
homepage: https://pypi.org/project/bandit/
licenses:
  - Apache license
languages:
  - Python
categories:
  - Linter

source:
  id: pkg:pypi/bandit@1.7.10

bin:
  bandit: pypi:bandit
